from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import numpy as np

from .ir import CallNode, TraceIR
from .serialize import serializeValue, DEFAULT_ARRAY_INLINE_THRESHOLD


def generateScript(
    trace_ir: TraceIR,
    path: str | Path | None = None,
    *,
    array_threshold: int = DEFAULT_ARRAY_INLINE_THRESHOLD,
) -> str:
    lines: list[str] = []

    lines.append('#!/usr/bin/env python3')
    lines.append('"""Auto-generated by tracer — reproduces the traced matplotlib figure."""')
    lines.append("")

    emitted_imports: set[str] = set()

    has_numpy = _irUsesNumpy(trace_ir)
    if has_numpy:
        lines.append("import numpy as np")
        emitted_imports.add("numpy")

    for imp in trace_ir.imports:
        code = imp.toCode()
        if code not in emitted_imports:
            lines.append(code)
            emitted_imports.add(code)

    lines.append("")

    inline_vars: dict[int, str] = {}  # id(array) → variable name
    inline_defs: list[str] = []
    _extractInlineArrays(trace_ir, inline_vars, inline_defs, array_threshold)

    if trace_ir.data_arrays:
        lines.append("# --- External data ---")
        for name in trace_ir.data_arrays:
            lines.append(f'{name} = np.load("{name}.npy")')
        lines.append("")

    if inline_defs:
        lines.append("# --- Data ---")
        lines.extend(inline_defs)
        lines.append("")

    lines.append("# --- Plot ---")
    for call in trace_ir.calls:
        line = _renderCall(call, trace_ir, inline_vars, array_threshold)
        lines.append(line)

    lines.append("")  # trailing newline
    script = "\n".join(lines)

    if path is not None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(script, encoding="utf-8")

        for name, arr in trace_ir.data_arrays.items():
            npy_path = path.parent / f"{name}.npy"
            np.save(str(npy_path), arr)

    return script


def _irUsesNumpy(trace_ir: TraceIR) -> bool:
    for call in trace_ir.calls:
        for arg in call.args:
            if isinstance(arg, np.ndarray):
                return True
        for val in call.kwargs.values():
            if isinstance(val, np.ndarray):
                return True
    if trace_ir.data_arrays:
        return True
    return False


def _extractInlineArrays(
    trace_ir: TraceIR,
    inline_vars: dict[int, str],
    inline_defs: list[str],
    array_threshold: int,
) -> None:
    min_extract_size = 10  # don't bother extracting very small arrays.
    counter = [0]  # mutable counter local to this code-gen pass.

    for call in trace_ir.calls:
        for arg in call.args:
            _maybeExtract(arg, trace_ir, inline_vars, inline_defs, min_extract_size, array_threshold, counter)
        for val in call.kwargs.values():
            _maybeExtract(val, trace_ir, inline_vars, inline_defs, min_extract_size, array_threshold, counter)


def _maybeExtract(
    value: Any,
    trace_ir: TraceIR,
    inline_vars: dict[int, str],
    inline_defs: list[str],
    min_size: int,
    array_threshold: int,
    counter: list[int],
) -> None:
    if isinstance(value, (list, tuple)):
        for item in value:
            _maybeExtract(item, trace_ir, inline_vars, inline_defs, min_size, array_threshold, counter)
        return

    if not isinstance(value, np.ndarray) or value.size<min_size:
        return
    arr_id = id(value)
    if arr_id in inline_vars:
        return
    name = f"data_{counter[0]}"
    counter[0] += 1
    inline_vars[arr_id] = name

    if value.size > array_threshold:
        trace_ir.data_arrays[name] = value
    else:
        code = serializeValue(value, trace_ir, array_threshold=array_threshold)
        inline_defs.append(f"{name} = {code}")


def _renderCall(
    call: CallNode,
    trace_ir: TraceIR,
    inline_vars: dict[int, str],
    array_threshold: int,
) -> str:
    if call.method == "__setitem__" and "rcParams" in call.target:
        key, value = call.args
        val_str = serializeValue(value, trace_ir, array_threshold=array_threshold)
        return f"plt.rcParams[{repr(key)}] = {val_str}"
    parts: list[str] = []
    for arg in call.args:
        parts.append(_serializeArg(arg, trace_ir, inline_vars, array_threshold))

    for key, val in call.kwargs.items():
        val_str = _serializeArg(val, trace_ir, inline_vars, array_threshold)
        parts.append(f"{key}={val_str}")

    args_str = ", ".join(parts)

    call_expr = f"{call.target}.{call.method}({args_str})"

    if call.return_var:
        return f"{call.return_var} = {call_expr}"
    return call_expr


def _serializeArg(
    value: Any,
    trace_ir: TraceIR,
    inline_vars: dict[int, str],
    array_threshold: int,
) -> str:
    if isinstance(value, np.ndarray) and id(value) in inline_vars:
        return inline_vars[id(value)]

    if isinstance(value, (list, tuple)):
        has_extracted = any(
            isinstance(item, np.ndarray) and id(item) in inline_vars
            for item in value
        )
        if has_extracted:
            inner = ", ".join(
                _serializeArg(item, trace_ir, inline_vars, array_threshold)
                for item in value
            )
            if isinstance(value, tuple):
                return f"({inner},)" if len(value) == 1 else f"({inner})"
            return f"[{inner}]"

    return serializeValue(value, trace_ir, array_threshold=array_threshold)
